SELECT C.NOME AS NOME_COLABORADOR,
       D.NOME AS NOME_DEPENDENTE,
       D.DATA_NASCIMENTO
FROM BRH.DEPENDENTE D
INNER JOIN BRH.COLABORADOR C ON C.MATRICULA = D.COLABORADOR   
WHERE extract(month from D.data_nascimento) in (4,5,6) 
  OR upper(D.nome) like '%H%'
ORDER BY C.NOME, D.NOME ;


select nome as nome_colaborador ,salario 
from brh.colaborador 
WHERE salario=(select max(salario) from brh.colaborador) 
ORDER BY  salario desc


select  matricula, nome salario ,case 
when salario<=3000 then 'Junior'
when salario>3000 and salario<=6000 then 'Pleno'
when salario>6000 and salario<=20000 then 'Senior'
else 'Diretor'
end as nivel
from brh.colaborador
order by  nivel,nome


SELECT D.NOME,
       P.NOME,
       COUNT(C.MATRICULA) AS QUANTIDADE_COLABORADORES
FROM BRH.PROJETO P
INNER JOIN BRH.ATRIBUICAO A ON P.ID = A.PROJETO
INNER JOIN BRH.COLABORADOR C ON A.COLABORADOR = C.MATRICULA
INNER JOIN BRH.DEPARTAMENTO D ON D.SIGLA = C.DEPARTAMENTO
GROUP BY D.NOME,
         P.NOME
ORDER BY D.NOME,
         P.NOME ;


SELECT C.NOME, COUNT(D.COLABORADOR) AS QTD_DEPENDENTES
FROM BRH.COLABORADOR C 
INNER JOIN BRH.DEPENDENTE D
ON C.MATRICULA = D.COLABORADOR
GROUP BY C.NOME
HAVING COUNT(D.COLABORADOR) > 1
ORDER BY QTD_DEPENDENTES DESC,
         C.NOME ;


SELECT D.NOME AS DEPARTAMENTO,
       CH.NOME AS CHEFE,
       CO.NOME AS COLABORADOR,
       PR.NOME AS PROJETO,
       PA.NOME AS PAPEL,
       T.NUMERO AS TELEFONE,
       DEP.NOME AS DEPENDENTE
FROM BRH.ATRIBUICAO A
INNER JOIN BRH.PROJETO PR ON A.PROJETO = PR.ID
INNER JOIN BRH.PAPEL PA ON A.PAPEL = PA.ID
INNER JOIN BRH.COLABORADOR CO ON A.COLABORADOR = CO.MATRICULA
INNER JOIN BRH.DEPARTAMENTO D ON CO.DEPARTAMENTO = D.SIGLA
INNER JOIN BRH.COLABORADOR CH ON D.CHEFE = CH.MATRICULA
INNER JOIN BRH.TELEFONE_COLABORADOR T ON CO.MATRICULA = T.COLABORADOR
INNER JOIN BRH.DEPENDENTE DEP ON CO.MATRICULA = DEP.COLABORADOR
ORDER BY PROJETO, COLABORADOR, DEPENDENTE ;